#!/usr/bin/env python3
"""Held-out check of the LiDAR box fitting in gpu_ground_segmentation.

The L-shape fitting and the size-prior completion were designed on the
hand-built scene (seed 0). This script runs that scene and fresh held-out
scenes (--seed N > 0: new box positions, headings and car / van sizes, new
sensor poses), collects one row per box observation, and compares the box
methods per observation with exact two-sided sign tests.

Writes <out>.csv (all observations) and <out>.md (the report).
"""

import argparse
import csv
import io
import math
from fractions import Fraction
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

METHODS = [
    ("lshape", "L-shape"),
    ("aabb", "axis-aligned"),
    ("prior", "L-shape + size prior"),
    ("prior_x0.9", "prior 10% too small"),
    ("prior_x1.1", "prior 10% too large"),
    ("prior_noend", "prior without the end-view rule"),
    ("prior_mlp", "L-shape + size prior, learned class"),
]

# (a, b, metric, lower is better): is a better than b?
COMPARISONS = [
    ("lshape", "aabb", "yaw", True),
    ("lshape", "aabb", "iou", False),
    ("prior", "lshape", "iou", False),
    ("prior", "lshape", "centre", True),
    ("prior_x0.9", "lshape", "iou", False),
    ("prior_x1.1", "lshape", "iou", False),
    ("prior", "prior_noend", "iou", False),
    ("prior_mlp", "prior", "iou", False),
    ("prior_mlp", "prior", "centre", True),
    ("prior_mlp", "lshape", "iou", False),
]

LABEL = dict(METHODS)
METRIC = {"yaw": "heading error", "iou": "BEV IoU", "centre": "centre error"}


def find_binary():
    for rel in ("bin/Release/gpu_ground_segmentation.exe", "bin/gpu_ground_segmentation"):
        path = os.path.join(ROOT, rel)
        if os.path.exists(path):
            return path
    sys.exit("gpu_ground_segmentation binary not found; build it first")


def run_seed(binary, seed, tmp_csv):
    cmd = [binary, "--no-video", "--seed", str(seed), "--obs-csv", tmp_csv]
    subprocess.run(cmd, cwd=ROOT, check=True, stdout=subprocess.DEVNULL)
    with open(tmp_csv, newline="") as f:
        return list(csv.DictReader(f))


def sign_test(wins, losses):
    n = wins + losses
    if n == 0:
        return 1.0
    k = min(wins, losses)
    p = float(Fraction(sum(math.comb(n, i) for i in range(k + 1)), 2 ** n))   # exact for large n
    return min(1.0, 2.0 * p)


def summarize(rows):
    out = []
    n = len(rows)
    for key, label in METHODS:
        iou = [float(r["iou_" + key]) for r in rows]
        out.append({
            "method": label,
            "yaw": sum(float(r["yaw_" + key]) for r in rows) / n,
            "iou": sum(iou) / n,
            "good": sum(v >= 0.5 for v in iou),
            "centre": sum(float(r["centre_" + key]) for r in rows) / n,
        })
    return out


def compare(rows):
    out = []
    for a, b, metric, lower in COMPARISONS:
        wins = losses = ties = 0
        diff = 0.0
        for r in rows:
            va, vb = float(r["%s_%s" % (metric, a)]), float(r["%s_%s" % (metric, b)])
            diff += va - vb
            if abs(va - vb) < 1e-9:
                ties += 1
            elif (va < vb) == lower:
                wins += 1
            else:
                losses += 1
        # observations of one seed share objects, so also compare per-seed means
        seed_w = seed_l = 0
        for seed in sorted({r["seed"] for r in rows}):
            d = sum(float(r["%s_%s" % (metric, a)]) - float(r["%s_%s" % (metric, b)])
                    for r in rows if r["seed"] == seed)
            if abs(d) < 1e-9:
                continue
            if (d < 0) == lower:
                seed_w += 1
            else:
                seed_l += 1
        out.append({
            "a": LABEL[a], "b": LABEL[b], "metric": METRIC[metric], "diff": diff / len(rows),
            "wins": wins, "losses": losses, "ties": ties, "p": sign_test(wins, losses),
            "seed_w": seed_w, "seed_l": seed_l, "seed_p": sign_test(seed_w, seed_l),
        })
    return out


def classes(rows, col):
    cars = [r for r in rows if int(r["box"]) <= 2]
    vans = [r for r in rows if int(r["box"]) == 4]
    return (sum(r[col] == "0" for r in cars), len(cars),
            sum(r[col] == "1" for r in vans), sum(r[col] == "0" for r in vans), len(vans))


def report(sets):
    w = io.StringIO()
    w.write("# LiDAR box fitting: dev scene vs held-out scenes\n\n")
    w.write("Generated by `scripts/box_fitting_heldout.py` from `gpu_ground_segmentation --seed N --obs-csv`.\n")
    w.write("Seed 0 is the hand-built scene the L-shape fitting and the size prior were designed on. "
            "Seeds > 0 are held-out scenes, with new box positions (within 1 m), headings, car / van sizes "
            "(cars 4.0-5.0 x 1.7-1.9 m, van 5.5-6.5 x 1.9-2.1 m; the prior stays 4.5 x 1.8 and 6.0 x 2.0) "
            "and sensor poses. One observation is one ground-truth box found as a cluster in one scan.\n")
    for name, rows in sets:
        w.write("\n## %s (%d observations)\n\n" % (name, len(rows)))
        w.write("| Box | heading error | BEV IoU | IoU >= 0.5 | centre error |\n|---|---:|---:|---:|---:|\n")
        for s in summarize(rows):
            w.write("| %s | %.2f deg | %.3f | %d | %.2f m |\n" % (s["method"], s["yaw"], s["iou"], s["good"], s["centre"]))
        w.write("\n")
        for col, name in (("cls", "Height rule"), ("cls_mlp", "Learned class")):
            car_ok, cars, van_ok, van_car, vans = classes(rows, col)
            w.write("%s: %d / %d car observations classed as cars; of %d van observations, %d as vans and %d as "
                    "cars.\n\n" % (name, car_ok, cars, vans, van_ok, van_car))
        multi = len({r["seed"] for r in rows}) > 1
        w.write("\n| Comparison | metric | mean difference | observations better / worse / tie | sign test p |")
        w.write(" seeds better / worse | seed sign test p |\n" if multi else "\n")
        w.write("|---|---|---:|---:|---:|" + ("---:|---:|\n" if multi else "\n"))
        for c in compare(rows):
            w.write("| %s vs %s | %s | %+.3f | %d / %d / %d | %.2g |"
                    % (c["a"], c["b"], c["metric"], c["diff"], c["wins"], c["losses"], c["ties"], c["p"]))
            w.write(" %d / %d | %.2g |\n" % (c["seed_w"], c["seed_l"], c["seed_p"]) if multi else "\n")
    return w.getvalue()


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--seeds", type=int, default=20, help="held-out seeds 1..N")
    ap.add_argument("--out", default="docs/results/box_fitting_heldout_2026-10-05")
    args = ap.parse_args()
    binary = find_binary()
    tmp = os.path.join(ROOT, "tmp")
    os.makedirs(tmp, exist_ok=True)
    tmp_csv = os.path.join(tmp, "box_obs.csv")
    dev = run_seed(binary, 0, tmp_csv)
    held = []
    for seed in range(1, args.seeds + 1):
        held += run_seed(binary, seed, tmp_csv)
        print("seed %d: %d observations so far" % (seed, len(held)))
    out = os.path.join(ROOT, args.out)
    with open(out + ".csv", "w", newline="") as f:
        wr = csv.DictWriter(f, fieldnames=list(dev[0].keys()))
        wr.writeheader()
        wr.writerows(dev + held)
    text = report([("Dev scene (seed 0)", dev), ("Held-out scenes (seeds 1-%d)" % args.seeds, held)])
    with open(out + ".md", "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(text)


if __name__ == "__main__":
    main()
