#!/usr/bin/env python3
"""Current performance of the LiDAR object pipeline (gpu_ground_segmentation).

Runs the current build on held-out scenes (seeds 1-20 by default) and writes
one summary: ground segmentation, clustering, boxes (single scan, tracked,
motion tracker, hybrid), the class per sensor height, velocity errors, identity
switches, and the time per scan. Every number comes from this run, with the
class in use. Writes <out>.md.
"""

import argparse
import csv
import io
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from box_fitting_heldout import ROOT, find_binary  # noqa: E402

VEH = {"0", "1", "2", "4"}
VEH_MOVING = {"0", "1", "2", "4", "7", "8"}


def run(binary, args, csv_path=None, cls_path=None):
    cmd = [binary, "--no-video"] + args
    if csv_path:
        cmd += ["--obs-csv", csv_path]
    if cls_path:
        cmd += ["--cls-csv", cls_path]
    out = subprocess.run(cmd, cwd=ROOT, check=True, capture_output=True, text=True).stdout
    rows = list(csv.DictReader(open(csv_path, newline=""))) if csv_path else []
    cls = list(csv.DictReader(open(cls_path, newline=""))) if cls_path else []
    return out, rows, cls


def mean(v):
    return sum(v) / len(v) if v else float("nan")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--seeds", default="1-20")
    ap.add_argument("--heights", default="0.8,1.2,1.8,2.5")
    ap.add_argument("--out", default="docs/results/lidar_objects_summary_2026-10-06")
    args = ap.parse_args()
    binary = find_binary()
    tmp = os.path.join(ROOT, "tmp")
    os.makedirs(tmp, exist_ok=True)
    obs, cls_csv = os.path.join(tmp, "summary_obs.csv"), os.path.join(tmp, "summary_cls.csv")
    a, b = (int(x) for x in args.seeds.split("-"))
    seeds = range(a, b + 1)

    f1, f1_thr, found, objects = [], [], 0, 0
    single, lshape, aabb, refined = [], [], [], []
    tracked, motion, hybrid, single_drive, verr_m, verr_p = [], [], [], [], [], []
    switches_motion, timing = 0, []
    per_height = {}
    for seed in seeds:
        out, rows, _ = run(binary, ["--seed", str(seed)], obs)
        m = re.findall(r"concentric-zone model : precision \S+  recall \S+  F1 (\S+)", out)
        f1.append(float(m[0]))
        f1_thr.append(float(re.findall(r"height threshold      : precision \S+  recall \S+  F1 (\S+)", out)[0]))
        g = re.search(r"concentric-zone model : objects found\s+(\d+) /\s+(\d+)", out)
        found += int(g.group(1)); objects += int(g.group(2))
        for r in rows:
            if r["box"] in VEH:
                single.append(float(r["iou_prior_mlp"])); lshape.append(float(r["iou_lshape"]))
                refined.append(float(r["iou_fs"]))
                aabb.append(float(r["iou_aabb"]))
        _, rows, _ = run(binary, ["--sequence", "--seed", str(seed)], obs)
        tracked += [float(r["iou_trk_prior"]) for r in rows if r["box"] in VEH]
        out, rows, _ = run(binary, ["--moving", "--seed", str(seed)], obs)
        for r in rows:
            if r["box"] not in VEH_MOVING:
                continue
            motion.append(float(r["iou_mtrk_prior"])); hybrid.append(float(r["iou_hybrid"]))
            single_drive.append(float(r["iou_prior_mlp"]))
            if float(r["verr_motion"]) >= 0:
                (verr_m if float(r["speed"]) > 0 else verr_p).append(float(r["verr_motion"]))
        switches_motion += int(re.search(r"motion tracker: \d+ tracks, \d+ true boxes tracked, (\d+) identity", out).group(1))
        t = re.search(r"^pipeline\s+([\d.]+) /\s+([\d.]+) ms", out, re.M)
        timing.append((float(t.group(1)), float(t.group(2))))
        for h in args.heights.split(","):
            _, rows, cls = run(binary, ["--seed", str(seed), "--sensor-height", h], obs, cls_csv)
            P = per_height.setdefault(h, {"car": [0, 0], "van": [0, 0], "other": [0, 0], "iou": []})
            for r in cls:
                k = {"0": "car", "1": "van", "2": "other"}[r["label"]]
                P[k][1] += 1
                P[k][0] += (r["mlp"] == r["label"]) if k != "other" else (r["mlp"] != "2")
            P["iou"] += [float(r["iou_prior_mlp"]) for r in rows if r["box"] in VEH]
        print("seed %d done" % seed)

    w = io.StringIO()
    w.write("# LiDAR object pipeline: current performance\n\n")
    w.write("Generated by `scripts/lidar_objects_summary.py` with the class in use, on held-out scenes and drives "
            "(seeds %s; sensor 1.8 m unless a height is given). Boxes: the vehicles' (cars and the van; on the "
            "`--moving` drives also the traffic), completed with the size prior.\n\n" % args.seeds)
    w.write("| Stage | measure | value |\n|---|---|---:|\n")
    w.write("| ground segmentation | F1 (height threshold for reference) | %.3f (%.3f) |\n" % (mean(f1), mean(f1_thr)))
    w.write("| clustering | objects found as one cluster | %d / %d (%.0f%%) |\n" % (found, objects, 100.0 * found / objects))
    w.write("| boxes, single scan | BEV IoU: axis-aligned / L-shape / + size prior / + free space | "
            "%.3f / %.3f / %.3f / %.3f |\n" % (mean(aabb), mean(lshape), mean(single), mean(refined)))
    w.write("| boxes, tracked along a drive | BEV IoU | %.3f |\n" % mean(tracked))
    w.write("| boxes, moving traffic | BEV IoU: single scan / motion tracker / hybrid | %.3f / %.3f / %.3f |\n"
            % (mean(single_drive), mean(motion), mean(hybrid)))
    w.write("| motion tracker | velocity error, moving / parked vehicles | %.2f / %.2f m/s |\n" % (mean(verr_m), mean(verr_p)))
    w.write("| motion tracker | identity switches over %d drives | %d |\n" % (len(seeds), switches_motion))
    w.write("| time per scan (`--moving`) | mean / max over the drives' scans, mean over drives | %.1f / %.1f ms |\n"
            % (mean([t[0] for t in timing]), mean([t[1] for t in timing])))
    w.write("\n| Sensor height | cars classed car | vans classed van | others classed car or van | box IoU with the prior |\n"
            "|---:|---:|---:|---:|---:|\n")
    for h, P in per_height.items():
        w.write("| %s m | %d / %d | %d / %d | %d / %d | %.3f |\n" % (h, P["car"][0], P["car"][1], P["van"][0], P["van"][1],
                                                                   P["other"][0], P["other"][1], mean(P["iou"])))
    with open(os.path.join(ROOT, args.out) + ".md", "w", encoding="utf-8", newline="\n") as f:
        f.write(w.getvalue())
    print(w.getvalue())


if __name__ == "__main__":
    main()
