#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a Markdown report from a repro-suite manifest.")
    parser.add_argument("--manifest", required=True, help="Input repro-suite manifest JSON.")
    parser.add_argument("--output", help="Output Markdown path. Defaults to report.md next to the manifest.")
    return parser.parse_args()


def repo_path(value: str) -> Path:
    path = Path(value)
    if path.is_absolute():
        return path
    return ROOT / path


def link_from(output_path: Path, value: str | None) -> str:
    if not value:
        return ""
    target = repo_path(value)
    try:
        return str(target.relative_to(output_path.parent))
    except ValueError:
        return str(target)


def status_counts(tasks: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for task in tasks:
        status = str(task.get("status", "unknown"))
        counts[status] = counts.get(status, 0) + 1
    return counts


def table_row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


def link_cell(output_path: Path, label: str, value: str | None) -> str:
    if not value:
        return ""
    return f"[{label}]({link_from(output_path, value)})"


def render_command_section(task: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    commands = task.get("commands", {})
    if not isinstance(commands, dict) or not commands:
        return lines

    lines.append("<details>")
    lines.append(f"<summary>{task.get('name', 'task')} commands</summary>")
    lines.append("")
    for step_name, command in commands.items():
        if not isinstance(command, dict):
            continue
        display = str(command.get("display", ""))
        returncode = command.get("returncode")
        duration = command.get("duration_s")
        lines.append(f"### {step_name}")
        lines.append("")
        if returncode is not None:
            lines.append(f"Return code: `{returncode}`")
            lines.append("")
        if duration is not None:
            lines.append(f"Duration: `{duration}s`")
            lines.append("")
        lines.append("```bash")
        lines.append(display)
        lines.append("```")
        lines.append("")
    lines.append("</details>")
    lines.append("")
    return lines


def render_report(manifest: dict[str, Any], output_path: Path) -> str:
    tasks = manifest.get("tasks", [])
    if not isinstance(tasks, list):
        raise RuntimeError("Manifest field `tasks` must be a list")

    counts = status_counts(tasks)
    lines: list[str] = []
    lines.append("# Repro Suite Report")
    lines.append("")
    lines.append("_Generated by `python3 scripts/render_repro_report.py`._")
    lines.append("")
    lines.append("## Run")
    lines.append("")
    lines.append(table_row(["Field", "Value"]))
    lines.append(table_row(["---", "---"]))
    for key in (
        "status",
        "suite",
        "git_commit",
        "created_at",
        "finished_at",
        "output_dir",
    ):
        lines.append(table_row([key, str(manifest.get(key, ""))]))
    lines.append(table_row(["dry_run", str(manifest.get("dry_run", ""))]))
    lines.append(table_row(["build_enabled", str(manifest.get("build_enabled", ""))]))
    lines.append(table_row(["summary_enabled", str(manifest.get("summary_enabled", ""))]))
    lines.append(table_row(["plots_enabled", str(manifest.get("plots_enabled", ""))]))
    lines.append("")

    lines.append("## Status Summary")
    lines.append("")
    lines.append(table_row(["Status", "Count"]))
    lines.append(table_row(["---", "---:"]))
    for status, count in sorted(counts.items()):
        lines.append(table_row([status, str(count)]))
    lines.append("")

    lines.append("## Tasks")
    lines.append("")
    lines.append(
        table_row(
            [
                "Task",
                "Status",
                "Target",
                "Optional",
                "Duration",
                "CSV",
                "Summary",
                "Logs",
            ]
        )
    )
    lines.append(table_row(["---", "---", "---", "---", "---:", "---", "---", "---"]))
    for task in tasks:
        outputs = task.get("outputs", {})
        commands = task.get("commands", {})
        csv_path = outputs.get("csv") if isinstance(outputs, dict) else None
        summary_path = outputs.get("summary") if isinstance(outputs, dict) else None
        log_links: list[str] = []
        if isinstance(commands, dict):
            for step_name, command in commands.items():
                if isinstance(command, dict) and command.get("log"):
                    log_links.append(link_cell(output_path, str(step_name), str(command["log"])))
        lines.append(
            table_row(
                [
                    str(task.get("name", "")),
                    str(task.get("status", "")),
                    str(task.get("target", "")),
                    str(task.get("optional", "")),
                    str(task.get("duration_s", "")),
                    link_cell(output_path, "csv", str(csv_path)) if csv_path else "",
                    link_cell(output_path, "summary", str(summary_path)) if summary_path else "",
                    ", ".join(log_links),
                ]
            )
        )
    lines.append("")

    lines.append("## Commands")
    lines.append("")
    for task in tasks:
        lines.extend(render_command_section(task))
    return "\n".join(lines).rstrip() + "\n"


def render_report_file(manifest_path: Path, output_path: Path) -> None:
    manifest = json.loads(manifest_path.read_text())
    if manifest.get("schema_version") != 1:
        raise RuntimeError("Only repro-suite manifest schema_version 1 is supported")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_report(manifest, output_path))


def main() -> int:
    args = parse_args()
    manifest_path = Path(args.manifest).resolve()
    output_path = Path(args.output).resolve() if args.output else manifest_path.with_name("report.md")
    render_report_file(manifest_path, output_path)
    print(f"Generated {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
