#!/usr/bin/env python3
"""Train the learned cluster class of gpu_ground_segmentation's box completion.

Runs gpu_ground_segmentation on training scenes (seeds 101-200 by default,
disjoint from the evaluation scenes: seed 0 and held-out seeds 1-20), collects
six features of every cluster's L-shape box (--cls-csv) with its class (car,
van, or none: any other cluster), trains a 6-16-3 tanh MLP with softmax
cross-entropy (numpy, full-batch Adam, fixed seed), and writes the weights to
include/lidar_box_classifier.h.

With --eval-seeds it also reports the confusion of the height rule and of the
MLP on evaluation scenes (run after rebuilding with the new header).
"""

import argparse
import csv
import os
import subprocess
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FEATS = ["long", "short", "height", "log_n", "range", "top_margin_deg"]
CLASSES = ["car", "van", "none"]
HEADER = os.path.join(ROOT, "include", "lidar_box_classifier.h")


def find_binary():
    for rel in ("bin/Release/gpu_ground_segmentation.exe", "bin/gpu_ground_segmentation"):
        path = os.path.join(ROOT, rel)
        if os.path.exists(path):
            return path
    sys.exit("gpu_ground_segmentation binary not found; build it first")


def collect(binary, seeds):
    tmp = os.path.join(ROOT, "tmp")
    os.makedirs(tmp, exist_ok=True)
    path = os.path.join(tmp, "box_cls.csv")
    rows = []
    for seed in seeds:
        subprocess.run([binary, "--no-video", "--seed", str(seed), "--cls-csv", path],
                       cwd=ROOT, check=True, stdout=subprocess.DEVNULL)
        with open(path, newline="") as f:
            rows += list(csv.DictReader(f))
    x = np.array([[float(r[k]) for k in FEATS] for r in rows], dtype=np.float64)
    y = np.array([int(r["label"]) for r in rows])
    rule = np.array([int(r["rule"]) for r in rows])
    mlp = np.array([int(r["mlp"]) for r in rows])
    return x, y, rule, mlp


def train(x, y, hidden=16, epochs=4000, lr=0.01, seed=0):
    mean, std = x.mean(0), x.std(0) + 1e-6
    xs = (x - mean) / std
    rng = np.random.default_rng(seed)
    params = {
        "W1": rng.normal(0, 1 / np.sqrt(xs.shape[1]), (hidden, xs.shape[1])), "b1": np.zeros(hidden),
        "W2": rng.normal(0, 1 / np.sqrt(hidden), (3, hidden)), "b2": np.zeros(3),
    }
    m = {k: np.zeros_like(v) for k, v in params.items()}
    v = {k: np.zeros_like(p) for k, p in params.items()}
    onehot = np.eye(3)[y]
    for t in range(1, epochs + 1):
        h = np.tanh(xs @ params["W1"].T + params["b1"])
        z = h @ params["W2"].T + params["b2"]
        z -= z.max(1, keepdims=True)
        p = np.exp(z)
        p /= p.sum(1, keepdims=True)
        dz = (p - onehot) / len(y)
        dh = (dz @ params["W2"]) * (1 - h ** 2)
        grads = {"W2": dz.T @ h, "b2": dz.sum(0), "W1": dh.T @ xs, "b1": dh.sum(0)}
        for k in params:
            m[k] = 0.9 * m[k] + 0.1 * grads[k]
            v[k] = 0.999 * v[k] + 0.001 * grads[k] ** 2
            params[k] -= lr * (m[k] / (1 - 0.9 ** t)) / (np.sqrt(v[k] / (1 - 0.999 ** t)) + 1e-8)
    return mean, std, params


def predict(x, mean, std, params):
    h = np.tanh(((x - mean) / std) @ params["W1"].T + params["b1"])
    return (h @ params["W2"].T + params["b2"]).argmax(1)


def write_header(mean, std, params, seeds, n):
    def arr(a):
        return "{ " + ", ".join("%.9gf" % float(e) for e in a) + " }"

    def mat(a):
        return "{\n" + "".join("    " + arr(row) + ",\n" for row in a) + "}"

    with open(HEADER, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by scripts/train_box_classifier.py; do not edit.\n")
        f.write("// 6-16-3 tanh MLP over L-shape box features (%s) -> car, van, none.\n" % ", ".join(FEATS))
        f.write("// Trained on %d clusters of gpu_ground_segmentation --seed %d..%d.\n" % (n, seeds[0], seeds[-1]))
        f.write("#pragma once\n\nnamespace lidar_box_classifier {\n")
        f.write("static const int N_IN = 6, N_HID = %d, N_OUT = 3;\n" % params["b1"].size)
        f.write("static const float MEAN[N_IN] = %s;\n" % arr(mean))
        f.write("static const float STD[N_IN] = %s;\n" % arr(std))
        f.write("static const float W1[N_HID][N_IN] = %s;\n" % mat(params["W1"]))
        f.write("static const float B1[N_HID] = %s;\n" % arr(params["b1"]))
        f.write("static const float W2[N_OUT][N_HID] = %s;\n" % mat(params["W2"]))
        f.write("static const float B2[N_OUT] = %s;\n" % arr(params["b2"]))
        f.write("}  // namespace lidar_box_classifier\n")


def confusion(y, pred):
    c = np.zeros((3, 3), dtype=int)
    for a, b in zip(y, pred):
        c[a, b] += 1
    return c


def print_confusion(name, y, pred):
    c = confusion(y, pred)
    print("%s: accuracy %.3f" % (name, (c.trace()) / c.sum()))
    print("  true \\ predicted  " + "  ".join("%6s" % k for k in CLASSES))
    for i, k in enumerate(CLASSES):
        print("  %-17s " % k + "  ".join("%6d" % e for e in c[i]))


def seed_range(text):
    a, b = text.split("-")
    return list(range(int(a), int(b) + 1))


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--train-seeds", default="101-200")
    ap.add_argument("--eval-seeds", default="", help="e.g. 1-20: report confusion only (no training)")
    args = ap.parse_args()
    binary = find_binary()
    if args.eval_seeds:
        x, y, rule, mlp = collect(binary, seed_range(args.eval_seeds))
        print("%d clusters of seeds %s" % (len(y), args.eval_seeds))
        print_confusion("height rule", y, rule)
        print_confusion("learned (MLP)", y, mlp)
        return
    seeds = seed_range(args.train_seeds)
    x, y, rule, _ = collect(binary, seeds)
    print("%d training clusters: %s" % (len(y), ", ".join("%s %d" % (k, (y == i).sum()) for i, k in enumerate(CLASSES))))
    mean, std, params = train(x, y)
    print_confusion("height rule (training scenes)", y, rule)
    print_confusion("learned (training scenes)", y, predict(x, mean, std, params))
    write_header(mean, std, params, seeds, len(y))
    print("wrote", os.path.relpath(HEADER, ROOT))


if __name__ == "__main__":
    main()
